name: STEST

on:
  workflow_dispatch:

env:
  fu: ${{ secrets.FU }}

jobs:
  ## upload artifact with fu as content
  ## create a json file with fu as content
  ## upload artifact with json file
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Create artifact
        run: |
          echo ${{ env.fu }} > fu
          cat fu
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: fu
          path: fu
